name: "default-backup-policy"
description: "Backup policy for all servers"
archive_interval: 48h
snapshot_frequency: "daily"
snapshot_time: "12:00"
bandwidth_limit: 100
snapshot_retention: 30
live_sync_frequency: 2m
transition_after_days: 30
delete_after_days: 90

targets:
  # Range pattern
  - pattern: "*"
    disks_excluded: 
      - "/dev/xvda"
