# Sample agent configuration
# mode: "agent"
# id: "agent2"
# dispatcher-addr: "localhost:8080"
# device: "/dev/nvme0n1"

# Sample dispatcher configuration
# mode: "dispatcher"
# data-dir: "/data"
# sync-freq: 3
# policy-dir: "/etc/blxrep/policies"

# Add user configuration for registration
# name: name of the user
# email: email of the user
# organization: org name
