# Sample agent configuration
# mode: "agent"
# id: "hostname"
# dispatcher-addr: "localhost:8080"

# Sample dispatcher configuration
# mode: "dispatcher"
# data-dir: "/data"
# policy-dir: "/etc/blxrep/policies"